modLoader="javafml"
loaderVersion="[${FORGE_LOADER_VERSION},)"
license="${MOD_LICENSE}"
issueTrackerURL="https://github.com/ApexModder/MultiPlatform-Template/issues"

[[mods]]
    modId="${MOD_ID}"
    version="${MOD_VERSION}"
    displayName="${MOD_NAME}"
    # updateJSONURL="https://api.modrinth.com/updates/<MODRINTH_PROJECT_ID>/forge_updates.json"
    displayURL="https://github.com/ApexModder/MultiPlatform-Template"
	# Uncomment if you have a banner/logo file
	# similar proprty exists for fabric.mod.json
	# "icon": "banner.png" - for fabric
    # logoFile="banner.png"
    credits="Apex - Programming"
    authors="ApexStudios"
    description="${MOD_DESCRIPTION}"

[[dependencies.${MOD_ID}]]
	modId="forge"
	mandatory=true
	versionRange="${FORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
	[dependencies.${MOD_ID}.custom.mc-publish]
		ignore=true
[[dependencies.${MOD_ID}]]
	modId="minecraft"
	mandatory=true
	versionRange="${MINECRAFT_FORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
	[dependencies.${MOD_ID}.custom.mc-publish]
		ignore=true
[[dependencies.${MOD_ID}]]
	modId="architectury"
	mandatory=true
	versionRange="${ARCHITECTURY_FORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
	[dependencies.${MOD_ID}.custom.mc-publish]
		modrinth="architectury-api"
		curseforge="architectury-api"
